# Generated by Django 4.1.7 on 2023-02-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='web',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
