# Generated by Django 4.1.7 on 2023-02-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_web_description_web_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='web/images/'),
        ),
    ]
